version: '3'

services:
  web:
    build:
      context: ./taskjo
      dockerfile: Dockerfile.prod
    command: >
          sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8080"
    volumes:
      - static_volume:/home/taskjo/web/staticfiles
      - media_volume:/home/taskjo/web/mediafiles
    # expose:
    #   - 8000
    ports:
      - "8060:8080"
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:latest

  celery:
    restart: always
    build:
      context: .
    # command: celery -A app worker -l info
    command: celery -A taskjo worker -B  -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./taskjo:/taskjo
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web

  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - static_volume:/home/taskjo/web/staticfiles
  #     - media_volume:/home/taskjo/web/mediafiles
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web

volumes:
  postgres_data:
  static_volume:
  media_volume: