version: '3'

services:
  # Django web server - celery master
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./taskjo:/taskjo
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8080"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    env_file:
      - ./.env.dev
    volumes: 
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    # ports:
    #  - '6379:6379'

  celery:
    restart: always
    build:
      context: .
    # command: celery -A app worker -l info
    command: celery -A taskjo worker -B  -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./taskjo:/taskjo
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app
  web:
    image: nginx
    volumes:
    - ./nginx/taskjo.conf:/etc/nginx/nginx.conf # TODO remove default
    ports:
    - "8090:80"
    
volumes:
  pgdata: