# Generated by Django 3.2 on 2022-06-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220624_1948'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='projects',
            field=models.ManyToManyField(blank=True, to='core.Projects', verbose_name='پروژه ها'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='موقعیت شغلی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='send_email',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='ارسال ایمیل'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='send_notification',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='ارسال ایمیل'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='send_sms',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='ارسال پیام کوتاه'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.Skill', verbose_name='مهارت ها'),
        ),
    ]
