# Generated by Django 3.2 on 2022-06-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220625_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='projects_count',
            field=models.IntegerField(default=0, verbose_name='تعداد پروژه امروز'),
        ),
    ]
