# Generated by Django 3.2 on 2022-07-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_projects_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name=' عکس پروفایل'),
        ),
    ]
