# Generated by Django 3.2 on 2022-06-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'کارفرما',
                'verbose_name_plural': 'کارفرما ها',
            },
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('star', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('project_count', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'وبسایت ها',
                'verbose_name_plural': 'وبسایت ها',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.websites')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price_min', models.IntegerField()),
                ('price_max', models.IntegerField()),
                ('budget', models.CharField(max_length=100)),
                ('remaining_time', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('state', models.SmallIntegerField(choices=[(0, 'OPEN'), (1, 'CLOSE')], default=0, editable=False)),
                ('applicants_number', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=100)),
                ('short_link', models.CharField(max_length=100)),
                ('long_link', models.CharField(max_length=100)),
                ('Website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.websites')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('employers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employer')),
                ('freelancers', models.ManyToManyField(to='core.Freelancer')),
                ('similar_projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projects')),
                ('skills', models.ManyToManyField(to='core.Skill')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.AddField(
            model_name='employer',
            name='Website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.websites'),
        ),
        migrations.AddField(
            model_name='category',
            name='Website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.websites'),
        ),
    ]
