# Generated by Django 3.2 on 2022-06-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.websites'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='employers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employer'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='freelancers',
            field=models.ManyToManyField(null=True, to='core.Freelancer'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='price_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='price_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='similar_projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='skills',
            field=models.ManyToManyField(null=True, to='core.Skill'),
        ),
    ]
