# Generated by Django 3.2 on 2022-06-18 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220617_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='freelancer',
            options={'verbose_name': 'فریلسنر', 'verbose_name_plural': 'فریلسنر ها'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='Website',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='Website',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='url',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='url',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='Website',
        ),
        migrations.RemoveField(
            model_name='websites',
            name='project_count',
        ),
        migrations.AddField(
            model_name='category',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.websites', verbose_name='وبسایت'),
        ),
        migrations.AddField(
            model_name='employer',
            name='employer_url',
            field=models.CharField(max_length=100, null=True, verbose_name='لینک کارفرما'),
        ),
        migrations.AddField(
            model_name='employer',
            name='employer_username',
            field=models.CharField(max_length=100, null=True, verbose_name='نام کاربری کارفرما'),
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.websites', verbose_name='وبسایت'),
        ),
        migrations.AddField(
            model_name='skill',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.websites', verbose_name='وبسایت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام فریلسنر'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='star',
            field=models.CharField(max_length=100, null=True, verbose_name='تعداد ستاره'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='لینک فریلسنر'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.websites', verbose_name='وبسایت'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='applicants_number',
            field=models.IntegerField(default=0, verbose_name='تعداد پیشنهاد'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='budget',
            field=models.CharField(default='0', max_length=100, verbose_name='بودجه'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='employers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employer', verbose_name='کارفرما'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='freelancers',
            field=models.ManyToManyField(to='core.Freelancer', verbose_name='فریلسنرها'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='long_link',
            field=models.CharField(max_length=100, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='price_max',
            field=models.IntegerField(default=0, verbose_name='حداکثر قیمت'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='price_min',
            field=models.IntegerField(default=0, verbose_name='حداقل قیمت'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='remaining_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='مهلت پروژه'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='short_link',
            field=models.CharField(max_length=100, verbose_name='لینک کوتاه'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='similar_projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projects', verbose_name='پروژه های مشابه'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='skills',
            field=models.ManyToManyField(to='core.Skill', verbose_name='مهارت ها'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'پروژه باز است'), (1, 'پروژه منقضی شده است')], default=0, editable=False, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آپدیت شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام مهارت'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام سایت'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='url',
            field=models.CharField(max_length=100, verbose_name='لینک سایت'),
        ),
    ]
