# Generated by Django 3.2 on 2022-06-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220618_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='long_link',
            field=models.CharField(max_length=300, verbose_name='لینک'),
        ),
    ]
