# Generated by Django 3.2 on 2022-06-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_projects_long_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Website',
            new_name='website',
        ),
        migrations.AlterUniqueTogether(
            name='projects',
            unique_together={('short_link',)},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'website')},
        ),
    ]
