# Generated by Django 3.2 on 2022-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220618_0706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='categories',
            new_name='categoriy',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='employers',
            new_name='employer',
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='لینک دسته بندی'),
        ),
        migrations.AddField(
            model_name='skill',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='لینک مهارت'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='employer_url',
            field=models.CharField(default='https://taskjo.ir/', max_length=100, verbose_name='لینک کارفرما'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='remaining_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت پروژه'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='url',
            field=models.URLField(max_length=100, verbose_name='لینک سایت'),
        ),
        migrations.AlterUniqueTogether(
            name='employer',
            unique_together={('employer_url',)},
        ),
    ]
