# Generated by Django 3.2 on 2022-06-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220620_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام مهارت'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='لینک مهارت'),
        ),
    ]
