# Generated by Django 3.2 on 2022-06-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220624_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='max_page',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' بیشترین تعداد صفحه جستجو'),
        ),
    ]
