# Generated by Django 3.2 on 2022-07-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_projects_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='categoriy',
            new_name='category',
        ),
    ]
