# Generated by Django 3.2 on 2022-07-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_categoriy_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_style_class',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='کلاس استایل مهارت'),
        ),
    ]
